version: "3.7"

services:
  
    
  flask:
    build: ./flask
    volumes:
       - ./checkpoint-4000:/app/checkpoint-4000
    expose: 
       - 5000
    ports:
       - "5000:5000"    
   

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on: 
      - flask 



